### ISSUE TITLE
Unhandled exception. System.UriFormatException: Invalid URI: The URI is empty.

### ISSUE THREAD

**Issue by ramonsmits** [Cohelion/CS.Changelog#3]
Just did:

    dotnet tool install -g CS.Changelog.Console

After that

    changelog

And this was the output:
```
Cohelion changelog generator, version 1.2.0.0
<?xml version="1.0" encoding="utf-16"?>
<Options xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ReleaseName />
  <PathToGit>git</PathToGit>
  <Full>false</Full>
  <StartTag />
  <RepositoryLocation />
  <Replace>false</Replace>
  <TargetFile>Changelog</TargetFile>
  <OpenFile>false</OpenFile>
  <OutputFormat>JSON</OutputFormat>
  <Verbosity>Info</Verbosity>
  <IssueNumberRegex>[a-zA-Z]{1,4}-\d{1,4}</IssueNumberRegex>
  <IssueTrackerUrl>https://projects.cohelion.com/issue/{0}</IssueTrackerUrl>
  <CommitDetailsUrl />
  <DontLinkifyIssueNumbers>false</DontLinkifyIssueNumbers>
  <Branch_development>develop</Branch_development>
  <Branch_master>master</Branch_master>
  <Branch_preview>preview</Branch_preview>
  <Prefix_hotfix>hotfix</Prefix_hotfix>
  <Prefix_release>release</Prefix_release>
  <Prefix_feature>feature</Prefix_feature>
  <Category_feature>Feature</Category_feature>
  <Category_hotfix>Hotfix</Category_hotfix>
</Options>
Reading history since tag : '0.12.4'
==(14-9-2023) ==

Unhandled exception. System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CS.Changelog.Exporters.JsonChangelogExporter.Export(ChangeSet changes, FileInfo file, ExportOptions options) in C:\BuildAgent\work\72ffad7c0d576719\CS.Changelog\Exporters\JsonChangelogExporter.cs:line 89
   at CS.Changelog.Exporters.ChangelogExportExtensions.Export(ChangeSet changes, OutputFormat format, String targetFile, ExportOptions exportOptions) in C:\BuildAgent\work\72ffad7c0d576719\CS.Changelog\Exporters\ChangelogExportExtensions.cs:line 68
   at CS.Changelog.Console.Program.Main(String[] args) in C:\BuildAgent\work\72ffad7c0d576719\CS.Changelog.Console\Program.cs:line 102
```

**Comment by Atrejoe** [comment]
@ramonsmits thanks for trying out this tool.
It has been used extensively in our operation, but possibly due to us specifying most of the argument, this slipped past us.
Looks like improper handling of a non-specified optional argument.

**Comment by Atrejoe** [comment]
@ramonsmits my fixes should address the issue, but you will have to wait until a colleague of mine publishes a new version to Nuget. (unless you are will to build the tool yourself).

@tecssil / @Aaltuj ?
